###  Loading Collection Data

In [1]:
import polars as pl
import gspread
from google.oauth2.service_account import Credentials
from sqlalchemy import create_engine,text
scope = ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]

creds = Credentials.from_service_account_file("../credentials.json", scopes=scope)
client = gspread.authorize(creds)

col_sheet_name = "Collection App Data"
col_sheet = client.open(col_sheet_name).worksheet('collection_data')

col_data = pl.DataFrame(col_sheet.get_all_records())

print("Collection Result successfully loaded!")
col_data.head()

Collection Result successfully loaded!

shape: (5, 13)
┌──────────┬───────────┬─────────────────┬─────────────────┬───┬────────────┬────────────┬─────────────────┬───────────┐
│ ID       ┆ Date      ┆ Agent Name      ┆ OUTLET NAME     ┆ … ┆ COLLECTION ┆ COLLECTION ┆ Closing Balance ┆ REMARKS   │
│ ---      ┆ ---       ┆ ---             ┆ ---             ┆   ┆ ---        ┆ TYPE       ┆ ---             ┆ ---       │
│ str      ┆ str       ┆ str             ┆ str             ┆   ┆ str        ┆ ---        ┆ str             ┆ str       │
│          ┆           ┆                 ┆                 ┆   ┆            ┆ str        ┆                 ┆           │
╞══════════╪═══════════╪═════════════════╪═════════════════╪═══╪════════════╪════════════╪═════════════════╪═══════════╡
│ 95406d34 ┆ 3/15/2026 ┆ panday.achyut@g ┆ Prayas Liquor   ┆ … ┆            ┆            ┆                 ┆ Followup  │
│          ┆           ┆ mail.com        ┆                 ┆   ┆            ┆            ┆                 ┆           │
│ 5d930857 ┆ 3/15/2026 ┆ yubrajsitaula4@ ┆ Jay Pathibhara  ┆ … ┆ 5000       ┆ Cash       ┆                 ┆ 55000     │
│          ┆           ┆ gmail.com       ┆ Maa Madira      ┆   ┆            ┆            ┆                 ┆           │
│          ┆           ┆                 ┆ Stor…           ┆   ┆            ┆            ┆                 ┆           │
│ 84aa7f27 ┆ 3/15/2026 ┆ anishkhadka046@ ┆ Seven Eleven    ┆ … ┆            ┆            ┆ 16000           ┆ Follow up │
│          ┆           ┆ gmail.com       ┆ Liquor Shop     ┆   ┆            ┆            ┆                 ┆           │
│ dfe69435 ┆ 3/15/2026 ┆ yubrajsitaula4@ ┆                 ┆ … ┆            ┆            ┆ 180000          ┆           │
│          ┆           ┆ gmail.com       ┆                 ┆   ┆            ┆            ┆                 ┆           │
│ 9db5b296 ┆ 3/15/2026 ┆ baralsuraj707@g ┆                 ┆ … ┆            ┆            ┆                 ┆ Closed    │
│          ┆           ┆ mail.com        ┆                 ┆   ┆            ┆            ┆                 ┆           │
└──────────┴───────────┴─────────────────┴─────────────────┴───┴────────────┴────────────┴─────────────────┴───────────┘

### Changing Collection and Closing Balance to Numbers and Date to Date

In [2]:
col_data = col_data.with_columns([
    pl.col('COLLECTION').cast(pl.Float32, strict=False),
    pl.col('Closing Balance').cast(pl.Float32, strict=False)
])

zero_cols = ['COLLECTION']

col_data = col_data.with_columns(
    pl.when(pl.col(z) == 0)
    .then(None)
    .otherwise(pl.col(z))
    .alias(z) 
    for z in zero_cols
)

col_data = col_data.with_columns([
    pl.col('Date').str.to_date(format="%m/%d/%Y")
])

### Aggregating OUTLET NAME AND NON-AGEING OUTLET to single column

In [3]:
col_data = col_data.with_columns(
    pl.when(
        ((pl.col("OUTLET NAME") == "") | pl.col("OUTLET NAME").is_null()) & 
        (pl.col("NON-AGEING OUTLET").is_not_null() & (pl.col("NON-AGEING OUTLET") != ""))
    )
    .then(pl.col("NON-AGEING OUTLET"))
    .otherwise(pl.col("OUTLET NAME"))
    .alias("Party Details")
)

### Cleaning Party Details Column

In [4]:
col_data = col_data.with_columns(
    pl.col("Party Details")
    .str.strip_chars()
    .str.to_uppercase()
    .str.replace_all(r"\s+", " ")
    .alias("Party Details")
)

### Check Duplicate Records for same date and same agent

In [5]:
duplicates = col_data.filter(
    pl.len().over(["Date", "Agent Name", "Party Details"]) > 1
).sort("Party Details")

duplicates

shape: (4, 14)
┌──────────┬────────────┬──────────────────┬──────────────────┬───┬────────────┬─────────┬──────────┬──────────────────┐
│ ID       ┆ Date       ┆ Agent Name       ┆ OUTLET NAME      ┆ … ┆ COLLECTION ┆ Closing ┆ REMARKS  ┆ Party Details    │
│ ---      ┆ ---        ┆ ---              ┆ ---              ┆   ┆ TYPE       ┆ Balance ┆ ---      ┆ ---              │
│ str      ┆ date       ┆ str              ┆ str              ┆   ┆ ---        ┆ ---     ┆ str      ┆ str              │
│          ┆            ┆                  ┆                  ┆   ┆ str        ┆ f32     ┆          ┆                  │
╞══════════╪════════════╪══════════════════╪══════════════════╪═══╪════════════╪═════════╪══════════╪══════════════════╡
│ 235842f0 ┆ 2026-03-15 ┆ yubrajsitaula4@g ┆ Devkota Brother  ┆ … ┆            ┆ 40000.0 ┆          ┆ DEVKOTA BROTHER  │
│          ┆            ┆ mail.com         ┆ Enterprises      ┆   ┆            ┆         ┆          ┆ ENTERPRISES      │
│ 0c061943 ┆ 2026-03-15 ┆ yubrajsitaula4@g ┆ Devkota Brother  ┆ … ┆ QR         ┆ 35000.0 ┆          ┆ DEVKOTA BROTHER  │
│          ┆            ┆ mail.com         ┆ Enterprises      ┆   ┆            ┆         ┆          ┆ ENTERPRISES      │
│ 6bd64560 ┆ 2026-03-16 ┆ panday.achyut@gm ┆ Thapaliya Liquor ┆ … ┆            ┆ null    ┆          ┆ THAPALIYA LIQUOR │
│          ┆            ┆ ail.com          ┆ Shop             ┆   ┆            ┆         ┆          ┆ SHOP             │
│ 80a9330e ┆ 2026-03-16 ┆ panday.achyut@gm ┆ Thapaliya Liquor ┆ … ┆            ┆ null    ┆ Followup ┆ THAPALIYA LIQUOR │
│          ┆            ┆ ail.com          ┆ Shop             ┆   ┆            ┆         ┆          ┆ SHOP             │
└──────────┴────────────┴──────────────────┴──────────────────┴───┴────────────┴─────────┴──────────┴──────────────────┘

### Handling Duplicates

In [6]:
col_data = col_data.with_row_index("original_idx")
cleaned_collection = (
    col_data
    .sort(
        ["Date", "Agent Name", "Party Details", "COLLECTION", "original_idx"], 
        descending=[False, False, False, False, False]
    )
    # nulls are sorted to the top by default in Polars (nulls_last=False)
    # so the record with a value in COLLECTION and the highest index 
    # will naturally be at the bottom of each group.
    .unique(
        subset=["Date", "Agent Name", "Party Details"], 
        keep="last", 
        maintain_order=True
    )
    .drop("original_idx") 
)

In [7]:
cleaned_collection.shape

(219, 14)

### Preparing collection data for insertion

In [8]:
from datetime import date,timedelta
collection_data = cleaned_collection.select(["ID","Date","Agent Name","Party Details","NON-AGEING OUTLET","ADDRESS",
                                             "STOCK SB","STOCK SR","STOCK RARA","COLLECTION","COLLECTION TYPE",
                                             "Closing Balance","REMARKS"])

yesterday = date.today() - timedelta(days=1)


yes_collection_data = collection_data.filter(pl.col('Date') == yesterday)
yes_collection_data.shape

(46, 13)

### Loading Collection Plan

In [9]:

plan_sheet = client.open("Ageing Report ").worksheet('Collection Plan')

plan_data = pl.DataFrame(plan_sheet.get_all_records(),infer_schema_length=None)

plan_data = plan_data.select(
    ['Area','Party Details','Closing Amt','Collection_Plan','Remarks','Sales_Agent'])

plan_data

shape: (1_226, 6)
┌────────────┬─────────────────────────────────┬─────────────┬─────────────────┬─────────┬─────────────┐
│ Area       ┆ Party Details                   ┆ Closing Amt ┆ Collection_Plan ┆ Remarks ┆ Sales_Agent │
│ ---        ┆ ---                             ┆ ---         ┆ ---             ┆ ---     ┆ ---         │
│ str        ┆ str                             ┆ f64         ┆ str             ┆ str     ┆ str         │
╞════════════╪═════════════════════════════════╪═════════════╪═════════════════╪═════════╪═════════════╡
│ BALAJU     ┆ B.R.Q Store                     ┆ 13830.07    ┆ 0               ┆         ┆ Unknown     │
│ BANEPA     ┆ Fame International              ┆ 35010.82    ┆ 0               ┆         ┆ Banepa      │
│ BANIYATAR  ┆ Grace Mini Mart And Suppliers   ┆ 13830.07    ┆ 0               ┆         ┆ Unknown     │
│ BASUNDHARA ┆ Ali Liquour Shop                ┆ 13830.07    ┆ 0               ┆         ┆ Unknown     │
│ BHAKTAPUR  ┆ Samjhana Wine Shop              ┆ 207392.6    ┆ 50000           ┆         ┆ Subash      │
│ …          ┆ …                               ┆ …           ┆ …               ┆ …       ┆ …           │
│ WEST3      ┆ Balaju Burgur House & Crunchy … ┆ 25510.0     ┆ 0               ┆         ┆ Shree       │
│ WEST3      ┆ Heartland Cafe Pvt.Ltd          ┆ 25510.0     ┆ 0               ┆         ┆ Shree       │
│ WEST3      ┆ Sindhupalchok Store             ┆ 13830.07    ┆ 0               ┆         ┆ suman       │
│            ┆ Amuprastha Mart Pvt.Ltd         ┆ 19067.54    ┆ 0               ┆         ┆ Kanchan     │
│            ┆ TOTALS                          ┆ 7.1338e7    ┆ 12782713        ┆         ┆             │
└────────────┴─────────────────────────────────┴─────────────┴─────────────────┴─────────┴─────────────┘

### Converting Data types and cleaning Party Details

In [10]:
float_cols = ['Closing Amt','Collection_Plan']
plan_data = plan_data.with_columns([
    pl.col(x).cast(pl.Float32,strict = False)
    for x in float_cols
])

plan_data = plan_data.with_columns(
    pl.col("Party Details")
    .str.strip_chars()
    .str.to_uppercase() 
    .str.replace_all(r"\s+", " ")
    .alias("Party Details")
)

plan_data = plan_data.filter(
    ~pl.col('Party Details').str.contains(r"(?i)^totals?$"),
    pl.col('Party Details').is_not_null(),
    pl.col('Party Details') != ""
)

plan_data = (
    plan_data
    # 1. Sort by Party Details, then by Collection_Plan descending.
    # This puts non-null/higher values at the top for each party.
    .sort("Party Details", "Collection_Plan", descending=[False, True])
    .unique(subset=["Party Details"], keep="first")
)


plan_data

shape: (1_225, 6)
┌───────────┬──────────────────────────┬──────────────┬─────────────────┬───────────┬─────────────┐
│ Area      ┆ Party Details            ┆ Closing Amt  ┆ Collection_Plan ┆ Remarks   ┆ Sales_Agent │
│ ---       ┆ ---                      ┆ ---          ┆ ---             ┆ ---       ┆ ---         │
│ str       ┆ str                      ┆ f32          ┆ f32             ┆ str       ┆ str         │
╞═══════════╪══════════════════════════╪══════════════╪═════════════════╪═══════════╪═════════════╡
│ East1     ┆ 3 D ENTERPRISES          ┆ 46540.238281 ┆ 0.0             ┆           ┆ Unknown     │
│ PATAN     ┆ 3 G HONCHA               ┆ 19620.050781 ┆ 0.0             ┆           ┆ Ishwar      │
│ BHAKTAPUR ┆ 3 K INTERNATIONAL        ┆ 20910.050781 ┆ 0.0             ┆ Bad Debts ┆ Subash      │
│ EAST1     ┆ A A A SUPPLIERS          ┆ 289983.96875 ┆ 0.0             ┆           ┆ Kanchan     │
│ BHAKTAPUR ┆ A B LIQUOR SHOP          ┆ 18006.230469 ┆ 5000.0          ┆           ┆ Subash      │
│ …         ┆ …                        ┆ …            ┆ …               ┆ …         ┆ …           │
│ PATAN     ┆ YOGESH STORE             ┆ 26240.089844 ┆ 0.0             ┆           ┆ Ishwar      │
│ BHAKTAPUR ┆ YOUR CHOICE LIQUOR STORE ┆ 13120.019531 ┆ 0.0             ┆           ┆ Subash      │
│ EAST1     ┆ YOURS DRINKS GALLERY     ┆ 24986.699219 ┆ 0.0             ┆           ┆ Kanchan     │
│ EAST2     ┆ YUB LIQUOR SHOP          ┆ 45940.121094 ┆ 13000.0         ┆           ┆ Nirmal      │
│ WEST1     ┆ ZAARA MART PVT.LTD       ┆ 12356.669922 ┆ 0.0             ┆           ┆ Shree       │
└───────────┴──────────────────────────┴──────────────┴─────────────────┴───────────┴─────────────┘

### Creating and testing postgres connection engine

In [11]:
con_url = "postgresql://postgres:postgres@localhost:5432/Collections_NSN"
engine = create_engine(con_url)

In [12]:
with engine.begin() as connection: 
    result = connection.execute(text("select * from party_collection_plans"))
    rows = result.keys()
    print(rows)
    connection.close()

RMKeyView(['id', 'party_details', 'area', 'sales_agent', 'closing_amt', 'collection_plan', 'remarks'])

### Mapping Dataframe headers with table headers

In [13]:
collection_mapping = {
    "ID": "id",
    "Date": "date",
    "Agent Name": "agent_name",
    "Party Details": "party_details",
    "NON-AGEING OUTLET": "non_ageing_outlet",
    "ADDRESS": "address",
    "STOCK SB": "stock_sb",
    "STOCK SR": "stock_sr",
    "STOCK RARA": "stock_rara",
    "COLLECTION": "collection",
    "COLLECTION TYPE": "collection_type",
    "Closing Balance": "closing_balance",
    "REMARKS": "remarks"
}

plan_mapping = {
    "Party Details": "party_details",
    "Closing Amt": "closing_amt",
    "Collection_Plan": "collection_plan",
    "Remarks": "remarks",
    "Area" : "area",
    "Sales_Agent" : "sales_agent"
}

### Inserting into collection_data

In [14]:
col_len = len(yes_collection_data)
import time
start_time = time.time()
try:
    with engine.begin() as connection:
        delete_stmt = text("DELETE FROM collection_data WHERE date = :val")
        connection.execute(delete_stmt, {"val": yesterday})
        print(f"Cleaned up existing records for {yesterday}")
    yes_collection_data.rename(collection_mapping).write_database(
        table_name = "collection_data",
        connection = con_url,
        if_table_exists = "append"
    )
    final_time = time.time()- start_time
    print(f"Collection data of {yesterday} inserted successfully. It has {col_len} records")
    print(f"Time taken to insert in collection_data : {final_time : .2f} seconds")
except Exception as e:
    print(f"An error occurred: {e}")

Cleaned up existing records for 2026-03-19
Collection data of 2026-03-19 inserted successfully. It has 46 records
Time taken to insert in collection_data :  6.34 seconds

### Inserting into party_collection_plan

In [15]:
plan_len = len(plan_data)
start = time.time() 
try:
    with engine.begin() as conn:
        delete_stat = "TRUNCATE TABLE party_collection_plans"
        conn.execute(text(delete_stat))
        print("Party Collection Plan cleared")
    plan_data.rename(plan_mapping).write_database(
        table_name = "party_collection_plans",
        connection = con_url,
        if_table_exists = "append"
    )
    final_time = time.time() - start 
    print(f"party_collection_plans inserted successfully. It has {plan_len} records")
    print(f"Time taken to insert in party_collection_plans {final_time : .2f} seconds")
except Exception as e:
     print(f"An error occurred: {e}")

Party Collection Plan cleared
party_collection_plans inserted successfully. It has 1225 records
Time taken to insert in party_collection_plans  0.15 seconds

### Reading Actual Collection

In [16]:
import polars as pl
from polars import col

collection_sheet = client.open('Actual Collection Data').worksheet('Chaitra_082')
records = collection_sheet.get_all_records()
act_col = pl.DataFrame(records, infer_schema_length=None)

act_col.columns = [
    'date',
    'outlet_name',
    'non-ageing_outlet',
    'code',
    'address',
    'zone',
    'cash_cheque',
    'amount',
    'agent'
]

act_col = (
    act_col
    .with_columns([
        pl.col("outlet_name").str.strip_chars(),
        pl.col("cash_cheque").str.to_lowercase().str.strip_chars(),
        pl.col("amount")
        .cast(pl.Utf8)
        .str.replace_all(",", "")
        .cast(pl.Float64, strict=False)
    ])
)

act_col = act_col.filter(
    (pl.col('date') != "") & 
    (
        (pl.col('outlet_name') != "") | 
        (pl.col('non-ageing_outlet') != "")
    )
)

act_col

shape: (9, 9)
┌────────────┬──────────────────────────────┬───────────────────┬──────┬───┬──────┬─────────────┬─────────┬───────┐
│ date       ┆ outlet_name                  ┆ non-ageing_outlet ┆ code ┆ … ┆ zone ┆ cash_cheque ┆ amount  ┆ agent │
│ ---        ┆ ---                          ┆ ---               ┆ ---  ┆   ┆ ---  ┆ ---         ┆ ---     ┆ ---   │
│ str        ┆ str                          ┆ str               ┆ str  ┆   ┆ str  ┆ str         ┆ f64     ┆ str   │
╞════════════╪══════════════════════════════╪═══════════════════╪══════╪═══╪══════╪═════════════╪═════════╪═══════╡
│ 2082-12-01 ┆ VAlley View Suppliers        ┆ Valley View       ┆      ┆ … ┆ 3    ┆ cash        ┆ 13120.0 ┆       │
│ 2082-12-01 ┆ R K Tudal Devi Liquor Outlet ┆                   ┆      ┆ … ┆ 3    ┆ cash        ┆ 11000.0 ┆       │
│ 2082-12-01 ┆ Crystal Store                ┆                   ┆      ┆ … ┆ 3    ┆ cash        ┆ 51020.0 ┆       │
│ 2082-12-01 ┆ Halesi Mart Pvt.ltd          ┆                   ┆      ┆ … ┆      ┆ cash        ┆ 31529.0 ┆       │
│ 2082-12-01 ┆ Kathmandu Online Liquor      ┆                   ┆      ┆ … ┆      ┆ cash        ┆ 6560.0  ┆       │
│ 2082-12-01 ┆ Sita Cold Store              ┆                   ┆      ┆ … ┆      ┆ cash        ┆ 3900.0  ┆       │
│ 2082-12-01 ┆ R Dream City Store           ┆                   ┆      ┆ … ┆      ┆ cash        ┆ 9000.0  ┆       │
│ 2082-12-01 ┆ Arab Liquor Shop             ┆                   ┆      ┆ … ┆      ┆ cash        ┆ 20000.0 ┆       │
│ 2082-12-01 ┆ R Dream City Store           ┆                   ┆      ┆ … ┆      ┆ cash        ┆ 30360.0 ┆       │
└────────────┴──────────────────────────────┴───────────────────┴──────┴───┴──────┴─────────────┴─────────┴───────┘

### Converting English Datetime to Nepali Datetime

In [17]:
import nepali_datetime
from datetime import datetime
act_col = act_col.with_columns(col('date').str.split('-').alias('date_parts'))



def bs_to_ad(date_list):
    yr = int(date_list[0])
    mon = int(date_list[1])
    day = int(date_list[2])
    nep_date = nepali_datetime.date(yr, mon, day)
    return nep_date.to_datetime_date()

act_col = act_col.with_columns(
    col('date_parts').map_elements(bs_to_ad,return_dtype = pl.Date).alias('english_date')
)

act_col

shape: (9, 11)
┌────────────┬────────────────────────┬───────────────────┬──────┬───┬─────────┬───────┬────────────────┬──────────────┐
│ date       ┆ outlet_name            ┆ non-ageing_outlet ┆ code ┆ … ┆ amount  ┆ agent ┆ date_parts     ┆ english_date │
│ ---        ┆ ---                    ┆ ---               ┆ ---  ┆   ┆ ---     ┆ ---   ┆ ---            ┆ ---          │
│ str        ┆ str                    ┆ str               ┆ str  ┆   ┆ f64     ┆ str   ┆ list[str]      ┆ date         │
╞════════════╪════════════════════════╪═══════════════════╪══════╪═══╪═════════╪═══════╪════════════════╪══════════════╡
│ 2082-12-01 ┆ VAlley View Suppliers  ┆ Valley View       ┆      ┆ … ┆ 13120.0 ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ R K Tudal Devi Liquor  ┆                   ┆      ┆ … ┆ 11000.0 ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆ Outlet                 ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ Crystal Store          ┆                   ┆      ┆ … ┆ 51020.0 ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ Halesi Mart Pvt.ltd    ┆                   ┆      ┆ … ┆ 31529.0 ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ Kathmandu Online       ┆                   ┆      ┆ … ┆ 6560.0  ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆ Liquor                 ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ Sita Cold Store        ┆                   ┆      ┆ … ┆ 3900.0  ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ R Dream City Store     ┆                   ┆      ┆ … ┆ 9000.0  ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ Arab Liquor Shop       ┆                   ┆      ┆ … ┆ 20000.0 ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
│ 2082-12-01 ┆ R Dream City Store     ┆                   ┆      ┆ … ┆ 30360.0 ┆       ┆ ["2082", "12", ┆ 2026-03-15   │
│            ┆                        ┆                   ┆      ┆   ┆         ┆       ┆ "01"]          ┆              │
└────────────┴────────────────────────┴───────────────────┴──────┴───┴─────────┴───────┴────────────────┴──────────────┘

In [18]:
import polars as pl

act_col = act_col.with_columns(
    pl.when(
        (pl.col('outlet_name').is_null() | (pl.col('outlet_name') == "")) & 
        (pl.col('non-ageing_outlet').is_not_null() & (pl.col('non-ageing_outlet') != ""))
    )
    .then(pl.col('non-ageing_outlet'))
    .otherwise(pl.col('outlet_name'))
    .alias('party_details')
)

act_col = act_col.drop(['date','date_parts','outlet_name','non-ageing_outlet'])

In [19]:
act_col = act_col.rename({'english_date' : 'date'})

In [20]:
act_col = act_col.with_columns(col('zone').cast(pl.Utf8))

act_col

shape: (9, 8)
┌──────┬─────────┬──────┬─────────────┬─────────┬───────┬────────────┬──────────────────────────────┐
│ code ┆ address ┆ zone ┆ cash_cheque ┆ amount  ┆ agent ┆ date       ┆ party_details                │
│ ---  ┆ ---     ┆ ---  ┆ ---         ┆ ---     ┆ ---   ┆ ---        ┆ ---                          │
│ str  ┆ str     ┆ str  ┆ str         ┆ f64     ┆ str   ┆ date       ┆ str                          │
╞══════╪═════════╪══════╪═════════════╪═════════╪═══════╪════════════╪══════════════════════════════╡
│      ┆         ┆ 3    ┆ cash        ┆ 13120.0 ┆       ┆ 2026-03-15 ┆ VAlley View Suppliers        │
│      ┆         ┆ 3    ┆ cash        ┆ 11000.0 ┆       ┆ 2026-03-15 ┆ R K Tudal Devi Liquor Outlet │
│      ┆         ┆ 3    ┆ cash        ┆ 51020.0 ┆       ┆ 2026-03-15 ┆ Crystal Store                │
│      ┆         ┆      ┆ cash        ┆ 31529.0 ┆       ┆ 2026-03-15 ┆ Halesi Mart Pvt.ltd          │
│      ┆         ┆      ┆ cash        ┆ 6560.0  ┆       ┆ 2026-03-15 ┆ Kathmandu Online Liquor      │
│      ┆         ┆      ┆ cash        ┆ 3900.0  ┆       ┆ 2026-03-15 ┆ Sita Cold Store              │
│      ┆         ┆      ┆ cash        ┆ 9000.0  ┆       ┆ 2026-03-15 ┆ R Dream City Store           │
│      ┆         ┆      ┆ cash        ┆ 20000.0 ┆       ┆ 2026-03-15 ┆ Arab Liquor Shop             │
│      ┆         ┆      ┆ cash        ┆ 30360.0 ┆       ┆ 2026-03-15 ┆ R Dream City Store           │
└──────┴─────────┴──────┴─────────────┴─────────┴───────┴────────────┴──────────────────────────────┘

### Cleaning Party Details for actual collection

In [21]:
act_col = act_col.with_columns(
    pl.col("party_details")
    .str.strip_chars()
    .str.to_uppercase() 
    .str.replace_all(r"\s+", " ")
    .alias("party_details")
)

act_col = act_col.filter(~(pl.col('party_details') == "") | (pl.col('party_details').is_null()))
act_col

shape: (9, 8)
┌──────┬─────────┬──────┬─────────────┬─────────┬───────┬────────────┬──────────────────────────────┐
│ code ┆ address ┆ zone ┆ cash_cheque ┆ amount  ┆ agent ┆ date       ┆ party_details                │
│ ---  ┆ ---     ┆ ---  ┆ ---         ┆ ---     ┆ ---   ┆ ---        ┆ ---                          │
│ str  ┆ str     ┆ str  ┆ str         ┆ f64     ┆ str   ┆ date       ┆ str                          │
╞══════╪═════════╪══════╪═════════════╪═════════╪═══════╪════════════╪══════════════════════════════╡
│      ┆         ┆ 3    ┆ cash        ┆ 13120.0 ┆       ┆ 2026-03-15 ┆ VALLEY VIEW SUPPLIERS        │
│      ┆         ┆ 3    ┆ cash        ┆ 11000.0 ┆       ┆ 2026-03-15 ┆ R K TUDAL DEVI LIQUOR OUTLET │
│      ┆         ┆ 3    ┆ cash        ┆ 51020.0 ┆       ┆ 2026-03-15 ┆ CRYSTAL STORE                │
│      ┆         ┆      ┆ cash        ┆ 31529.0 ┆       ┆ 2026-03-15 ┆ HALESI MART PVT.LTD          │
│      ┆         ┆      ┆ cash        ┆ 6560.0  ┆       ┆ 2026-03-15 ┆ KATHMANDU ONLINE LIQUOR      │
│      ┆         ┆      ┆ cash        ┆ 3900.0  ┆       ┆ 2026-03-15 ┆ SITA COLD STORE              │
│      ┆         ┆      ┆ cash        ┆ 9000.0  ┆       ┆ 2026-03-15 ┆ R DREAM CITY STORE           │
│      ┆         ┆      ┆ cash        ┆ 20000.0 ┆       ┆ 2026-03-15 ┆ ARAB LIQUOR SHOP             │
│      ┆         ┆      ┆ cash        ┆ 30360.0 ┆       ┆ 2026-03-15 ┆ R DREAM CITY STORE           │
└──────┴─────────┴──────┴─────────────┴─────────┴───────┴────────────┴──────────────────────────────┘

### Inserting into Actual_Collection

In [22]:
col_len = len(act_col)
import time
start_time = time.time()
try:
    with engine.begin() as connection:
        delete_stmt = text("TRUNCATE TABLE actual_collection")
        connection.execute(delete_stmt)
        print(f"Cleared actual_collection")
    act_col.write_database(
        table_name = "actual_collection",
        connection = con_url,
        if_table_exists = "append"
    )
    final_time = time.time()- start_time
    print(f"Actual_Collection inserted successfully. It has {col_len} records")
    print(f"Time taken to insert in collection_data : {final_time : .2f} seconds")
except Exception as e:
    print(f"An error occurred: {e}")

Cleared actual_collection
Actual_Collection inserted successfully. It has 9 records
Time taken to insert in collection_data :  0.11 seconds